/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ImpressumRouteImport } from './routes/Impressum'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as SignSignUpRouteImport } from './routes/sign/sign-up'
import { Route as SignSignInRouteImport } from './routes/sign/sign-in'
import { Route as EventsNewRouteImport } from './routes/events/new'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventsEventidRouteImport } from './routes/events/$eventid'
import { Route as EventsEventidIndexRouteImport } from './routes/events/$eventid.index'
import { Route as EventsEventidEditRouteImport } from './routes/events/$eventid.edit'

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/Impressum',
  path: '/Impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignSignUpRoute = SignSignUpRouteImport.update({
  id: '/sign/sign-up',
  path: '/sign/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignSignInRoute = SignSignInRouteImport.update({
  id: '/sign/sign-in',
  path: '/sign/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventidRoute = EventsEventidRouteImport.update({
  id: '/events/$eventid',
  path: '/events/$eventid',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventidIndexRoute = EventsEventidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventidRoute,
} as any)
const EventsEventidEditRoute = EventsEventidEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EventsEventidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Impressum': typeof ImpressumRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/not-found': typeof NotFoundRoute
  '/posts': typeof PostsRoute
  '/events/$eventid': typeof EventsEventidRouteWithChildren
  '/events/create': typeof EventsCreateRoute
  '/events/new': typeof EventsNewRoute
  '/sign/sign-in': typeof SignSignInRoute
  '/sign/sign-up': typeof SignSignUpRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventid/edit': typeof EventsEventidEditRoute
  '/events/$eventid/': typeof EventsEventidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Impressum': typeof ImpressumRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/not-found': typeof NotFoundRoute
  '/posts': typeof PostsRoute
  '/events/create': typeof EventsCreateRoute
  '/events/new': typeof EventsNewRoute
  '/sign/sign-in': typeof SignSignInRoute
  '/sign/sign-up': typeof SignSignUpRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventid/edit': typeof EventsEventidEditRoute
  '/events/$eventid': typeof EventsEventidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Impressum': typeof ImpressumRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/not-found': typeof NotFoundRoute
  '/posts': typeof PostsRoute
  '/events/$eventid': typeof EventsEventidRouteWithChildren
  '/events/create': typeof EventsCreateRoute
  '/events/new': typeof EventsNewRoute
  '/sign/sign-in': typeof SignSignInRoute
  '/sign/sign-up': typeof SignSignUpRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventid/edit': typeof EventsEventidEditRoute
  '/events/$eventid/': typeof EventsEventidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Impressum'
    | '/about'
    | '/calendar'
    | '/not-found'
    | '/posts'
    | '/events/$eventid'
    | '/events/create'
    | '/events/new'
    | '/sign/sign-in'
    | '/sign/sign-up'
    | '/events/'
    | '/events/$eventid/edit'
    | '/events/$eventid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Impressum'
    | '/about'
    | '/calendar'
    | '/not-found'
    | '/posts'
    | '/events/create'
    | '/events/new'
    | '/sign/sign-in'
    | '/sign/sign-up'
    | '/events'
    | '/events/$eventid/edit'
    | '/events/$eventid'
  id:
    | '__root__'
    | '/'
    | '/Impressum'
    | '/about'
    | '/calendar'
    | '/not-found'
    | '/posts'
    | '/events/$eventid'
    | '/events/create'
    | '/events/new'
    | '/sign/sign-in'
    | '/sign/sign-up'
    | '/events/'
    | '/events/$eventid/edit'
    | '/events/$eventid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpressumRoute: typeof ImpressumRoute
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  NotFoundRoute: typeof NotFoundRoute
  PostsRoute: typeof PostsRoute
  EventsEventidRoute: typeof EventsEventidRouteWithChildren
  EventsCreateRoute: typeof EventsCreateRoute
  EventsNewRoute: typeof EventsNewRoute
  SignSignInRoute: typeof SignSignInRoute
  SignSignUpRoute: typeof SignSignUpRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Impressum': {
      id: '/Impressum'
      path: '/Impressum'
      fullPath: '/Impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/sign-up': {
      id: '/sign/sign-up'
      path: '/sign/sign-up'
      fullPath: '/sign/sign-up'
      preLoaderRoute: typeof SignSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/sign-in': {
      id: '/sign/sign-in'
      path: '/sign/sign-in'
      fullPath: '/sign/sign-in'
      preLoaderRoute: typeof SignSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventid': {
      id: '/events/$eventid'
      path: '/events/$eventid'
      fullPath: '/events/$eventid'
      preLoaderRoute: typeof EventsEventidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventid/': {
      id: '/events/$eventid/'
      path: '/'
      fullPath: '/events/$eventid/'
      preLoaderRoute: typeof EventsEventidIndexRouteImport
      parentRoute: typeof EventsEventidRoute
    }
    '/events/$eventid/edit': {
      id: '/events/$eventid/edit'
      path: '/edit'
      fullPath: '/events/$eventid/edit'
      preLoaderRoute: typeof EventsEventidEditRouteImport
      parentRoute: typeof EventsEventidRoute
    }
  }
}

interface EventsEventidRouteChildren {
  EventsEventidEditRoute: typeof EventsEventidEditRoute
  EventsEventidIndexRoute: typeof EventsEventidIndexRoute
}

const EventsEventidRouteChildren: EventsEventidRouteChildren = {
  EventsEventidEditRoute: EventsEventidEditRoute,
  EventsEventidIndexRoute: EventsEventidIndexRoute,
}

const EventsEventidRouteWithChildren = EventsEventidRoute._addFileChildren(
  EventsEventidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpressumRoute: ImpressumRoute,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  NotFoundRoute: NotFoundRoute,
  PostsRoute: PostsRoute,
  EventsEventidRoute: EventsEventidRouteWithChildren,
  EventsCreateRoute: EventsCreateRoute,
  EventsNewRoute: EventsNewRoute,
  SignSignInRoute: SignSignInRoute,
  SignSignUpRoute: SignSignUpRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
